# 🔐 GitLeaks Configuration for Boilerplate Project
# Настройка детекции секретов в коде

# Заголовок
title = "Boilerplate GitLeaks Config"

# Базовые правила детекции
[extend]
# Использовать встроенные правила GitLeaks
useDefault = true

# Исключения (allowlist) - добавьте сюда ваши исключения
[[rules]]
id = "demo-credentials"
description = "Demo credentials in documentation"
regex = '''(admin123|demo-password|test-secret)'''
path = '''(README\.md|docs/.*\.md|\.env\.example)'''

# Игнорировать тестовые файлы с фиктивными данными
[[rules]]
id = "test-secrets"
description = "Test secrets in test files"
regex = '''(test-secret|mock-token|fake-key|dummy-password)'''
path = '''(test.*|.*test.*|.*\.test\..*)'''

# Исключить примеры конфигураций
[allowlist]
description = "Allowlisted files and patterns"

# Файлы для игнорирования
paths = [
    '''env\.example''',
    '''\.env\.template''',
    '''docs/.*\.md''',
    '''README\.md''',
    '''CHANGELOG\.md''',
    '''\.github/.*\.yml''',
    '''\.github/.*\.yaml''',
]

# Паттерны для игнорирования (регулярные выражения)
regexes = [
    # Demo/example credentials
    '''demo-secret-key''',
    '''example-password''',
    '''your-secret-here''',
    '''replace-me''',
    '''change-this''',
    
    # Test data
    '''test-.*-secret''',
    '''mock-.*-token''',
    '''fake-.*-key''',
    
    # Django secret key placeholders
    '''django-insecure-.*''',
    '''dev-secret''',
    
    # Common development placeholders
    '''localhost''',
    '''127\.0\.0\.1''',
    '''postgres:postgres''',
    '''admin:admin''',
]

# Коммиты для игнорирования (по хешу)
commits = []

# Расширенная конфигурация для специфичных правил
[[rules]]
id = "env-file-secrets"
description = "Actual secrets in .env files" 
regex = '''(?i)(.{0,40}(secret|key|token|password|pass|pwd).{0,40}=.{8,})'''
path = '''\.env$'''
tags = ["secret", "env"]

[[rules]]
id = "django-secret-key"
description = "Django secret key in settings"
regex = '''SECRET_KEY\s*=\s*["\'][^"\']{20,}["\']'''
path = '''settings.*\.py$'''
tags = ["django", "secret-key"]

# Кастомные правила для вашего проекта (раскомментируйте при необходимости)
# [[rules]]
# id = "custom-api-key"
# description = "Custom API keys"
# regex = '''your-api-pattern-here'''
# tags = ["api", "custom"]

# Глобальные исключения по расширениям файлов
[allowlist.regexTarget = "filename"]
regexes = [
    '''.*\.lock$''',    # Lock файлы (package-lock.json, pnpm-lock.yaml)
    '''.*\.log$''',     # Log файлы
    '''.*\.min\.js$''', # Минифицированные JS файлы
    '''.*\.map$''',     # Source map файлы
]

# 📝 АДАПТАЦИЯ ДЛЯ ВАШЕГО ПРОЕКТА:
#
# 1. 🎯 Кастомные правила:
#    - Добавьте специфичные для вашего проекта паттерны детекции
#    - Настройте правила для ваших API ключей, токенов
#
# 2. ⚪ Исключения:
#    - Добавьте в allowlist.regexes паттерны ваших demo данных  
#    - Исключите специфичные файлы и пути вашего проекта
#
# 3. 📂 Пути:
#    - Обновите allowlist.paths для ваших конфиг файлов
#    - Добавьте папки документации, примеров
#
# 4. 🏷️ Теги:
#    - Используйте теги для категоризации найденных секретов
#    - Настройте алерты по определенным тегам
#
# 5. 🔍 Тестирование:
#    - Запустите `gitleaks detect --source .` для тестирования
#    - Проверьте что нет false positives на ваших данных
