# Generated by Django 5.2.5 on 2025-09-03 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        choices=[("binance", "Binance"), ("okx", "OKX")],
                        help_text="Exchange name",
                        max_length=20,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("spot", "Spot Trading"),
                            ("futures", "Futures Trading"),
                            ("earn", "Earn/Staking"),
                        ],
                        default="spot",
                        help_text="Account type (only 'spot' enabled in MVP)",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-friendly name for this account", max_length=100
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="Exchange API key (stored as plaintext in MVP, encrypted in Step 8)",
                        max_length=200,
                    ),
                ),
                (
                    "api_secret",
                    models.CharField(
                        help_text="Exchange API secret (stored as plaintext in MVP, encrypted in Step 8)",
                        max_length=500,
                    ),
                ),
                (
                    "testnet",
                    models.BooleanField(
                        default=False, help_text="Use testnet/sandbox environment"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Account is active and can be used for trading",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_tested_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time API credentials were successfully tested",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Account",
                "verbose_name_plural": "Exchange Accounts",
                "ordering": ["-created_at"],
                "unique_together": {("user", "exchange", "account_type", "testnet")},
            },
        ),
    ]
