# Generated by Django 5.2.5 on 2025-09-03 08:33

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchanges", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ts",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when snapshot was taken",
                    ),
                ),
                (
                    "quote_asset",
                    models.CharField(
                        default="USDT",
                        help_text="Base currency for NAV calculation (e.g., USDT, USD, BTC)",
                        max_length=10,
                    ),
                ),
                (
                    "nav_quote",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Total Net Asset Value in quote currency",
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "positions",
                    models.JSONField(
                        help_text='Asset positions as {"BTC": {"amount": "0.12", "quote_value": "7234.50"}, ...}'
                    ),
                ),
                (
                    "prices",
                    models.JSONField(
                        blank=True,
                        help_text='Market prices at snapshot time as {"BTCUSDT": "60287.1", ...}',
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("summary", "User Summary Request"),
                            ("order_fill", "Order Execution"),
                            ("cron", "Periodic Snapshot"),
                            ("init", "Initial Backfill"),
                        ],
                        help_text="How this snapshot was created",
                        max_length=20,
                    ),
                ),
                (
                    "strategy_version",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Version of strategy when snapshot was taken (for future use)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exchange_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Exchange account for this snapshot (nullable if user has no accounts)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="exchanges.exchangeaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this portfolio snapshot",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio Snapshot",
                "verbose_name_plural": "Portfolio Snapshots",
                "ordering": ["-ts"],
                "indexes": [
                    models.Index(
                        fields=["user", "-ts"], name="portfolio_snapshot_user_ts"
                    ),
                    models.Index(
                        fields=["user", "exchange_account", "-ts"],
                        name="portfolio_snapshot_user_acc_ts",
                    ),
                    models.Index(
                        fields=["ts", "source"], name="portfolio_snapshot_ts_source"
                    ),
                ],
            },
        ),
    ]
