# Generated by Django 5.2.5 on 2025-09-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchanges", "0002_portfoliosnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangeaccount",
            name="passphrase",
            field=models.CharField(
                blank=True,
                help_text="Exchange API passphrase (required for OKX, optional for others)",
                max_length=200,
                null=True,
            ),
        ),
    ]
