# Generated by Django 5.2.5 on 2025-09-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchanges", "0004_add_portfolio_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangeaccount",
            name="last_error_at",
            field=models.DateTimeField(
                blank=True, help_text="Last error timestamp (UTC)", null=True
            ),
        ),
        migrations.AddField(
            model_name="exchangeaccount",
            name="last_error_code",
            field=models.CharField(
                blank=True,
                help_text="Last error code (e.g., 'AUTH_ERROR', 'RATE_LIMITED')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="exchangeaccount",
            name="last_latency_ms",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Last operation latency in milliseconds",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="exchangeaccount",
            name="last_success_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last successful operation timestamp (UTC)",
                null=True,
            ),
        ),
    ]
