# Generated by Django 5.2.5 on 2025-09-03 06:27

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="order_step_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.40"),
                help_text="Order step percentage for limit orders (0.4% = more aggressive pricing)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.MaxValueValidator(Decimal("5.00")),
                ],
            ),
        ),
    ]
