# Generated by Django 5.2.5 on 2025-09-04 09:16

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0004_switch_cancel_buffer_pct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="switch_cancel_buffer_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.15"),
                help_text="Absolute cancel buffer as percentage of price (0.15% default)",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1.00")),
                ],
            ),
        ),
    ]
