# Generated by Django 5.2.5 on 2025-09-06 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchanges", "0004_add_portfolio_state"),
        ("strategies", "0005_alter_strategy_switch_cancel_buffer_pct"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="exchange_account",
            field=models.ForeignKey(
                help_text="Коннектор для этой стратегии",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exchanges.exchangeaccount",
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="quote_asset",
            field=models.CharField(
                choices=[("USDT", "USDT"), ("USDC", "USDC"), ("BTC", "BTC")],
                default="USDT",
                help_text="Базовая валюта стратегии",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="user",
            field=models.ForeignKey(
                help_text="User who owns this strategy",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strategies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="strategy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("exchange_account",),
                name="one_active_strategy_per_connector",
            ),
        ),
    ]
