# Generated by Django 5.2.5 on 2025-09-06 03:22

from django.db import migrations


def populate_exchange_accounts(apps, schema_editor):
    """
    Populate exchange_account for existing strategies with user's first active ExchangeAccount.

    According to architecture doc: "Привязка к первому активному exchange_account пользователя"
    """
    Strategy = apps.get_model("strategies", "Strategy")
    ExchangeAccount = apps.get_model("exchanges", "ExchangeAccount")

    strategies_updated = 0
    strategies_without_accounts = 0

    for strategy in Strategy.objects.filter(exchange_account__isnull=True):
        # Find user's first active exchange account
        first_account = ExchangeAccount.objects.filter(
            user=strategy.user, is_active=True
        ).first()

        if first_account:
            strategy.exchange_account = first_account
            strategy.save(update_fields=["exchange_account"])
            strategies_updated += 1
            print(
                f"✓ Strategy '{strategy.name}' (user: {strategy.user.username}) → ExchangeAccount '{first_account.name}'"
            )
        else:
            strategies_without_accounts += 1
            print(
                f"⚠ Strategy '{strategy.name}' (user: {strategy.user.username}) → No active ExchangeAccount found"
            )

    print(
        f"Migration completed: {strategies_updated} strategies updated, {strategies_without_accounts} without accounts"
    )


def reverse_populate_exchange_accounts(apps, schema_editor):
    """Reverse migration - set exchange_account to NULL."""
    Strategy = apps.get_model("strategies", "Strategy")
    Strategy.objects.update(exchange_account=None)


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0006_update_strategy_fields"),
        ("exchanges", "0004_add_portfolio_state"),  # Dependency on exchanges
    ]

    operations = [
        migrations.RunPython(
            populate_exchange_accounts,
            reverse_populate_exchange_accounts,
        ),
    ]
