# Generated by Django 5.2.5 on 2025-09-06 03:34

import django.db.models.deletion
from django.db import migrations, models


def populate_null_exchange_accounts(apps, schema_editor):
    """
    Fill NULL exchange_account values with user's first active ExchangeAccount.
    Safe for production deployment.
    """
    Strategy = apps.get_model("strategies", "Strategy")
    ExchangeAccount = apps.get_model("exchanges", "ExchangeAccount")

    null_strategies = Strategy.objects.filter(exchange_account__isnull=True)
    strategies_updated = 0
    strategies_without_accounts = 0

    for strategy in null_strategies:
        # Find first active exchange account for user
        first_account = ExchangeAccount.objects.filter(
            user=strategy.user, is_active=True
        ).first()

        if first_account:
            strategy.exchange_account = first_account
            strategy.save(update_fields=["exchange_account"])
            strategies_updated += 1
        else:
            # No active accounts - this shouldn't happen in practice
            strategies_without_accounts += 1

    if strategies_updated > 0:
        print(
            f"Migration 0008: Populated {strategies_updated} strategies with exchange_account"
        )
    if strategies_without_accounts > 0:
        print(
            f"Migration 0008: WARNING - {strategies_without_accounts} strategies without active accounts"
        )


def reverse_populate_null_exchange_accounts(apps, schema_editor):
    """
    Reverse operation - set exchange_account to NULL.
    This should only be used for rollback testing.
    """
    # Don't actually nullify in reverse - too dangerous
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0007_populate_strategy_exchange_accounts"),
        ("exchanges", "0004_add_portfolio_state"),  # Ensure PortfolioState exists
    ]

    operations = [
        # First, populate NULL values
        migrations.RunPython(
            populate_null_exchange_accounts,
            reverse_populate_null_exchange_accounts,
        ),
        # Then, make field non-nullable
        migrations.AlterField(
            model_name="strategy",
            name="exchange_account",
            field=models.ForeignKey(
                help_text="Коннектор для этой стратегии",
                on_delete=django.db.models.deletion.CASCADE,
                to="exchanges.exchangeaccount",
            ),
        ),
    ]
