# Generated by Django 5.2.5 on 2025-09-07 05:06

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0008_make_exchange_account_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="min_delta_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.10"),
                help_text="Minimum delta as percentage of target value (0.01-10.00%) to trigger rebalancing",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.MaxValueValidator(Decimal("10.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="min_delta_quote",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="DEPRECATED: Minimum delta in quote currency (USDT) to trigger rebalancing",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
