# Generated by Django 5.2.5 on 2025-09-07 05:06

from decimal import Decimal

from django.db import migrations


def set_min_delta_pct_default(apps, schema_editor):
    """Set min_delta_pct to 0.1% for all existing strategies."""
    Strategy = apps.get_model("strategies", "Strategy")

    # Update all strategies to have min_delta_pct = 0.1%
    updated_count = Strategy.objects.update(min_delta_pct=Decimal("0.10"))
    print(f"Updated {updated_count} strategies with min_delta_pct=0.1%")


def reverse_set_min_delta_pct_default(apps, schema_editor):
    """Reverse migration - reset min_delta_pct to default."""
    Strategy = apps.get_model("strategies", "Strategy")

    # Reset to the model default (0.10)
    Strategy.objects.update(min_delta_pct=Decimal("0.10"))


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0009_add_min_delta_pct"),
    ]

    operations = [
        migrations.RunPython(
            set_min_delta_pct_default, reverse_set_min_delta_pct_default
        ),
    ]
