# Generated by Django 5.2.5 on 2025-09-07 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0010_set_min_delta_pct_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="strategy",
            name="min_delta_quote",
        ),
    ]
