# Generated by Django 5.2.5 on 2025-09-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0011_remove_min_delta_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="auto_trade_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable automatic trading for this strategy"
            ),
        ),
    ]
