# Generated by Django 5.2.5 on 2025-09-08 03:29

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0012_add_auto_trade_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="order_size_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="Order size as percentage of NAV (0.10-100.00%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.10")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
    ]
